# Generated by Django 5.2.6 on 2025-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para identificar la sucursal.', max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sucursal está operativa. Desmarcar en lugar de borrar para mantener la integridad de los datos históricos.')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=20, verbose_name='Número Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Interior/Local')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia/Barrio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado/Provincia')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('pais', models.CharField(default='México', max_length=50, verbose_name='País')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto de la sucursal.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto de la sucursal.', max_length=254, verbose_name='Correo Electrónico')),
                ('gerente', models.CharField(blank=True, help_text='Nombre del gerente o responsable de la sucursal.', max_length=150, verbose_name='Nombre del Gerente')),
                ('fecha_apertura', models.DateField(blank=True, help_text='Fecha en que la sucursal inició operaciones.', null=True, verbose_name='Fecha de Apertura')),
                ('rfc', models.CharField(blank=True, help_text='RFC de la sucursal para facturación. Debe ser único si se especifica.', max_length=13, null=True, unique=True, verbose_name='Registro Federal de Contribuyentes (RFC)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.', verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
